//____________________________________________________________________________________
//The following are imports used to create the app and its reactive data


//The following imports ‘Vue’ functions that initialized the ‘Vue’ application and created reactive data that automatically updates the screen when changed.
const { createApp, ref } = Vue;
//The following imports ‘Vuetify’, a UI framework that provides styling components like buttons, cards, and app-bars for creating pictures and titles.
const { createVuetify } = Vuetify;
//The following allows the ‘Vue’ app to use ‘Vuetify’ components and styling.
const vuetify = createVuetify();

//____________________________________________________________________________________
//The following are the main app components

//Everything inside this controls the behaviour of the whale interface.
const App = {
 setup() {
  const image = "whale.png"; //This is the image of the whale displayed in the main interface when you open up the module.
  const progress =ref(0); //’subjects’ is a reactive array wrapped in ref(), meaning that ‘Vue’ will track changes and automatically update the screen when the user interacts with the module and the data changes.

  //Each object in this array represents one clickable button placed on a body part of the whale, and when clicked, it opens an info card that will hold information on that body part and a relevant picture or embedded youtube video.
  const subjects = ref([
  { title: "Tail", //This is the button label, and in this case, it reads “Tail”.
    x: 78, y: 19, //These are the horizontal and vertical positions (respectively) of the info card.
    text1: "Whales use their tails to recognize and speak to one another across the ocean!", //This is the first line to appear in the info card. It is meant to catch the readers’ attention.
    //text2 is the next section of the info card, discussing some facts about whale’s tails and some indigenous traditions’ understanding of this body part’s significance.
    text2:"Powerful tail slaps on the ocean’s surface and 40km leaps forward send profound signals through the water to warn, court, or coordinate with other whales. Each tail is also uniquely patterned—like a fingerprint—allowing whales to identify each individual by its distinct ridges. This is why in many Indigenous traditions, a whale’s tail is more than a tool for movement; it’s a symbol of profound identity that reflects not only the whale’s individuality but also its role within a community.", 
    //text3 is the section after, discussing the human impacts on whales, referencing the effects on whale’s tails specifically.
    text3:"Today, however, whale identities—constructed through their tails—face profound threats from human activity.  Noise pollution from ships drown out whales’ water-borne signals, disrupting lines of communication. Climate change has reduced prey availability, forcing whales to travel greater distances and placing additional strain on their tails, thus weakening their strength. Exploitative practices (such as commercial whaling and entanglement in fishing gear) can injure or scar tails, compromising individual recognition.", 
    //text4 provides information to end the info card. However, for the next stage of this module’s development, we will seek to draw on traditional ecological knowledge to elaborate on the material impacts shipping routes and ships themselves have on whale tails.
    text4:"These impacts remind us that everyday human activities—things that may seem ordinary or harmless—can profoundly disrupt whales’ identities and the intricate social communities they rely on in the ocean.", 
    image: "WhaleTail.jpg", //This is the image that appears inside the info card. In this case, it is a picture of a whale’s tail corresponding to the info card’s topic of focus. 
    link: "https://www.raincoast.org/noisetracker/", //This the link contained in a “learn more” button on the card which encourages users to dive deeper into the information we’ve provided. In this case, it is a link to an organization called “Noise tracker” which seeks to monitor underwater noise production, research its effects on whales, and provide a platform for effective advocacy against the harming of whales.
    video: "https://www.youtube.com/watch?v=GOlghrCOJNQ", //Similar to the “learn more” button, we have embedded a youtube video to encourage users to continue learning while making the page feel more interactive. While the video displays in the card, it gives us an error message. Once we upload our project to Github, this error should be fixed. 
    clicked:false //”clicked” is a boolean flag that tracks whether the user has interacted with this subject. Initially set to “false” (meaning the subject has not been clicked yet), it is set to “true” when the user clicks on the icon button that the user would click on to open the cards.
  },
  //Eyes button & card. The code is the same as the “Tail” button, but this info card holds is about whale eyes.
  { title: "Eyes", x: 33, y: 53, text1:"Whales use their eyes not just to navigate, but to survive in the ocean’s ever‑changing world!", text2: "While living in dim and deep waters, many whale species have highly adapted eyes that detect subtle changes in light and contrast despite the world appearing to them in grey-scale. In some species, eyes positioned on the sides of the head provide a panoramic visual field of 130o without eye movement, while specialized retinal rod photoreceptor cells allow whales to see clearly both near the surface and in low-light depths. This is why, in many Indigenous traditions from the Pacific Northwest to Oceania, a whale’s eye is not merely an organ of sight but a symbol of wisdom. Whales are regarded as powerful, guardian-like beings whose gaze connects the physical and spiritual worlds, conveying knowledge that remains largely unknowable to humans.", text3:"Today, due to human activity, whale vision faces serious threats. Artificial light from coastal development, vessel traffic, and offshore infrastructure alters the ocean’s natural light and disrupts visual orientation. Water pollution also reduces clarity and fuels excess algal blooms, making navigation more hazardous. Ship strikes and entanglement in fishing gear can further injure or permanently damage a whale’s eyes, impairing vision entirely. These impacts serve as a stark reminder of how profoundly human activity can disrupt whales’ sensory worlds, affecting not only their survival but also their ability to guide the communities that look to them for wisdom.", image: "WhaleEyes.png", video: "https://www.youtube.com/watch?v=gAc-eLlGl88", link: "https://www.pbsnc.org/blogs/science/humpback-whales-see-less-than-we-thought/?fbclid=IwQ0xDSwMaVY1leHRuA2FlbQIxMQABHoZiB1X6ANU334YKWw57XrALU-HkmbnpWNVv_kkyZJeHyCYnJMVNMYM1cBUY_aem_6qwJuNrxYduC03zU0ThQCg", clicked:false },
  //Body button & card:
  { title: "Body", x: 57, y: 80, text1:"Humpback whales are among the largest animals on Earth! Their bodies can grow up to 18 meters long and weigh between 22,000 and 36,000 kilograms, with females often growing slightly larger than males. This immense size helps whales store energy, regulate body temperature, and travel thousands of kilometers. Their long, streamlined bodies also allow them to glide efficiently through the ocean while diving deeply and travelling great distances between feeding and breeding grounds. For these reasons, the whale’s broad body is understood in some Indigenous traditions as a symbol of carrying and protection. Oral teachings describe whales as beings strong enough to “carry the stories of the ocean,” their great bodies representing endurance and the responsibility of transporting knowledge.", text2:"Today, however, the very size that once empowered whales has made them increasingly vulnerable. Large whales cannot easily change direction when massive ships approach, and as global shipping traffic increases, collisions with vessels have become a major threat; ship strikes can cause devastating blunt-force trauma, breaking ribs, damaging internal organs, or leaving deep propeller wounds across a whale’s back. Entanglement in fishing gear can also wrap tightly around a whale’s torso, cutting into the skin and blubber as the animal swims and grows. Over time, this can deform the whale’s body, restrict movement, and drain energy needed for migration.", text3: "These impacts reveal how even the most powerful bodies in the ocean are also some of the most victimized.", image: "WhaleBody.png", video: "https://www.youtube.com/watch?v=glxULceEEjA", link:"https://iwc.int/management-and-conservation/vessel-strikes", clicked:false },
  //Finn button & card:
  { title: "Fin", x: 40, y: 50, text1:"Humpback whales are especially known for their remarkably long pectoral fins, which can grow up to one-third of their total body length—sometimes reaching nearly 4.5 meters! These fins act like wings underwater, allowing whales to turn sharply, stabilize their bodies, and maneuver with surprising precision despite their enormous size. The front edges of humpback fins also contain rounded bumps called tubercles, which help reduce drag and improve lift in the water, making swimming more efficient.", text2: "In many Indigenous traditions along the Pacific Northwest coast, whales’ powerful fins are associated with guidance and direction. Some teachings describe the fin as the part of the whale that helps it “choose its path,” symbolizing leadership and the ability to navigate life’s challenges.", text3:"Today, however, pectoral fins are often the first part of a whale to snag on fishing ropes, nets, or buoy lines. Entanglement can slice into the skin and blubber, permanently scar or deform the fin, and restrict its movement. Even partial damage to a fin can reduce the whale’s ability to steer, hunt, or migrate efficiently, which increases stress on the body as a whole. Recent monitoring in U.S. and Canadian waters indicates a sharp rise in entanglement cases affecting fins, particularly for humpbacks and right whales. Climate-driven changes in prey distribution also force whales to swim longer distances, placing additional strain on fins, especially if they have existing injuries.", image: "WhaleFin.png", video: "https://www.youtube.com/watch?v=SrG2m1IrhUc", link:"https://www.oreateai.com/blog/the-fascinating-world-of-whale-fins-names-and-functions/bf2ecadd6c442a4d199352d3ab2a79aa", clicked:false },
  //Reproductive system button & card:
  { title: "Reproductive system", x: 70, y: 59, text1:"Whales’ reproductive systems are central to the survival and continuity of their species. After an 11-month gestation period, female whales give birth to a single calf, which can measure 13 to 16 feet at birth! The calf stays with its protective mother for the first year, during which it learns to swim, feed, and navigate the ocean before being weaned. Female whales typically give birth every 2-3 years, although some may reproduce annually, demonstrating remarkable energy investment and resilience.", text2: "In many Indigenous traditions along the Pacific Northwest coast, whale mothers and calves are celebrated as living symbols of care, endurance, and the deep bonds that sustain life. The mother’s body is seen as both protector and teacher, guiding her calf through the ocean’s challenges while passing on the instincts, knowledge, and rhythms needed to survive. This relationship reflects a broader understanding of the ocean as a connected community, where each generation carries the lessons and stories of those that came before.", text3: "Today, however, human activity increasingly threatens whale reproduction. Noise pollution from ships and industrial activity can stress pregnant females, interfering with communication, migration, and feeding. Entanglement in fishing gear can also injure or separate mothers and calves, while climate-driven changes in prey distribution force mothers to swim longer distances, reducing the energy available for gestation and nursing. These impacts show that human activity does more than endanger individual whales—it disrupts the reproductive processes that sustain a whole population.", image: "WhaleReproduction.png", video: "https://www.youtube.com/watch?v=o767PuYbEXg", link: "https://apnews.com/article/right-whale-endangered-extinction-climate-aca9048d0df4faa4304c05534bd4acc9", clicked:false },
  //Tubercles button & card:
  { title: "Tubercles", x: 36, y: 87, text1:"A whale’s tubercles are the distinctive, golfball-sized bumps that line the upper and lower jaws, each housing its own hair follicle. While scientists are still uncovering the full purpose of these structures, they appear to serve as specialized sensory organs, helping whales detect subtle changes in their environment. One fascinating behavior linked to tubercles is the “seaweed facial”: humpbacks have been observed gathering clumps of floating seaweed from the surface and rubbing them against the areas of their rostrum where the tubercles are located. This interaction seems to provide a tactile pleasure for the whales, suggesting that tubercles may not only gather information but also play a role in playful behaviors!", text2: "In many Indigenous traditions, whale tubercles are regarded as symbols of individuality, intelligence, and perceptiveness. Each whale’s pattern of bumps is unique, reflecting its distinct character and its ability to interact thoughtfully with the environment.Therefore, oral histories describe whales as highly aware beings, sensitive to subtle changes in currents, prey, and the ocean around them—suggesting that Indigenous peoples recognized the significance of tubercles long before scientists studied them.", text3: "Today, sadly, human activity increasingly disrupts this sensitivity. Noise pollution from global oil or cargo shipping lanes, seismic testing, and offshore development are all said to interfere with a whale’s ability to focus and sense its surroundings; even minor disturbances in these behaviors may affect social learning, calf development, and overall well-being. These pressures show that even the tiniest features of a whale’s body—like tubercles—are essential not just to physical survival, but to the rich sensory life that defines their experience of the ocean.", image: "WhaleTubercles.png", video: "https://www.youtube.com/watch?v=zGqjyqXHIek", link: "https://biologyinsights.com/what-are-the-bumps-on-humpback-whales/?utm_source=chatgpt.com", clicked:false },
  ]);

//____________________________________________________________________________________
//The following are functions. A “function” is a set of instructions that performs a task when called, and the following code includes two functions: one for opening/closing info cards, and one for checking where the user clicks on the whale image.

//The following function ‘findCoordinates’ is used to determine where the user clicks on the whale image. A “function” is a set of instructions that performs a task when it is called, and in this case, the function calculates the position of a click as a percentage of the current browser window size, which is useful for placing buttons or interactive elements accurately on the whale image.
function findCoordinates(event) {
    const windowWidth = window.innerWidth; //This references the width of the browser window in pixels.
    const windowHeight = window.innerHeight; //This references the height of the browser window in pixels.
    //These next two lines convert the x and y pixel positions of the mouse click into percentages relative to the window size. This allows the coordinates to remain accurate even if the browser window is resized.
    const xPercent = (event.clientX / windowWidth) * 100;
    const yPercent = (event.clientY / windowHeight) * 100;
    //The following then prints the calculated percentages to the console for debugging. This is helpful when adding new clickable areas (buttons) on the whale image, as it allows precise positioning.
    console.log(`X: ${xPercent.toFixed(2)}%, Y: ${yPercent.toFixed(2)}%`);
} 

//The following function ‘updateProgress’ tracks the user when they interact with the body part info card buttons: it ensures that the progress bar only increases the first time a button is clicked and does not increase if an info card is revisited. Without this check, repeatedly clicking on the same button would incorrectly increase the progress multiple times.
function updateProgress(index){
   if (!subjects.value[index].clicked) {  //This signals to only increment progress if the button is clicked and has not been clicked before.
   subjects.value[index].clicked = true; //Marks the button as clicked so it cannot increment if clicked again.
   const increment = 100 / subjects.value.length; //Calculates how much each button contributes to the total progress of the bar. 
   progress.value = Math.min(progress.value + increment, 100); //Updates the progress, making sure it never exceeds 100%.
 }
}

//In Vue, the “return” statement exposes reactive variables and functions to the HTML template. Without returning them, the HTML template cannot access or use these values. Therefore, here, we are returning the main data and functions for the app:
 return {
   subjects, //refers to the array of the whale body parts, so that buttons and info cards can appear on the page.
   image, //so the whale image can be displayed in HTML.
   findCoordinates, //The function for detecting where a user clicks on the image, usable in the template.
   progress, //The reactive progress value, so the progress bar can update automatically.
   updateProgress //The function for updating progress when a subject is clicked, callable from the template.
  }
 }
}

//This final step tells Vue to: (1) create the app using the ‘App’ component defined above, (2) install Vuetify, allowing the use of styled buttons, cards, and other Material Design components, and (3) mount the app to the HTML element with id="app".Without this, nothing would appear on the page.
createApp(App).use(vuetify).mount('#app');


